config/routes.rb
require 'api_version'

Rails.application.routes.draw do

  root 'welcome#home'

  scope defaults: { format: 'json' } do
    namespace :api do
      scope module: :v1, constraints: ApiVersion.new('v1', true) do
        resources :systems
      end
    end
  end
 
  resources :systems
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/system.rb
class System < ApplicationRecord
end

app/controllers/api/v1/systems_controller.rb
module Api
  module V1

    class SystemsController < VersionController
      before_action :set_system, only: [:show, :update, :destroy]
    
      # GET /systems
      def index
        @systems = System.all
      end
    
      # GET /systems/1
      def show
      end
    
      def create
      # POST /systems
        @system = System.find_by(name: params[:system][:name])
        
        respond_to do |format|
          if @system
            if compare_params
              format.json { render :show, status: :created, location: @system }
            else
              if @system.update(system_params)
                format.json { render :show, status: :ok, location: @system }
              else
                format.json { render json: @system.errors, status: :unprocessable_entity }
              end         
            end
          else
            @system = System.new(system_params)
      
            if @system.save
              format.json { render :show, status: :ok, location: @system }
            else
              format.json { render json: @system.errors, status: :unprocessable_entity }
            end
          end
        end
      end
  
      # PATCH/PUT /systems/1
      def update
        respond_to do |format|
          if @system.update(system_params)
            format.json { render :show, status: :ok, location: @system }
          else
            format.json { render json: @system.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /systems/1
      def destroy
        @system.destroy
        respond_to do |format|
          format.html { redirect_to systems_url, notice: 'System was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        def compare_params
          [params["name"],
           params["resource_group"],
           params["availability_set"],
           params["operating_system"],
           params["vm_size"],
           params["operating_system_version"],
           params["storage"],
           params["subnet"],
           params["ip"],
           params["nsg"],
           params["nsg_resource_group"],
           params["location"]].uniq == 
          [@system.name,
           @system.resource_group,
           @system.availability_set,
           @system.operating_system,
           @system.vm_size,
           @system.storage,
           @system.subnet,
           @system.ip,
           @system.nsg,
           @system.nsg_resource_group,
           @system.location]
        end
        
        # Use callbacks to share common setup or constraints between actions.
        def set_system
          @system = System.find(params[:id])
        end
    
        # Only allow a trusted parameter "white list" through.
        def system_params
          params.require(:system).permit(:name, 
                                        :resource_group, 
                                        :availability_set, 
                                        :operating_system, 
                                        :vm_size, 
                                        :operating_system_version, 
                                        :storage, 
                                        :subnet, 
                                        :ip, 
                                        :nsg, 
                                        :nsg_resource_group,
                                        :location)
        end
    end
  end
end

app/controllers/api/v1/version_controller.rb
module Api::V1
  class VersionController < ApplicationController
    abstract!
    protect_from_forgery with: :null_session
    #skip_before_action :verify_authenticity_token
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy]

  # GET /systems
  # GET /systems.json
  def index
    @q = System.ransack(params[:q])
    @q.sorts = 'name asc' if @q.sorts.empty?
    @systems = @q.result.page(params[:page])
  	@q.build_condition
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
  end

  # GET /systems/new
  def new
    @system = System.new
  end

  # GET /systems/1/edit
  def edit
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(system_params)

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render :show, status: :created, location: @system }
      else
        format.html { render :new }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /systems/1
  # PATCH/PUT /systems/1.json
  def update
    respond_to do |format|
      if @system.update(system_params)
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { render :show, status: :ok, location: @system }
      else
        format.html { render :edit }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system.destroy
    respond_to do |format|
      format.html { redirect_to systems_url, notice: 'System was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_params
      params.require(:system).permit(:name, :resource_group, :availability_set, :operating_system, :vm_size, :operating_system_version, :storage, :subnet, :ip, :nsg, :nsg_resource_group)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @systems = System.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resources</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/systems/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Systems</h1>

<%= search_form_for @q do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>  
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>   
  <%= f.submit "Search", class: 'btn btn-primary' %>
<% end %>

<%= paginate @systems %>
<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= sort_link(@q, :resource_group, "Resouce Group") %></th>
      <th><%= sort_link(@q, :location) %></th>
      <th><%= sort_link(@q, :availability_set, "Availability Set") %></th>
      <th><%= sort_link(@q, :operating_system, "OS") %></th>
      <th><%= sort_link(@q, :vm_size, "VM Size") %></th>
      <th><%= sort_link(@q, :operating_system_version, "OS Version") %></th>
      <th><%= sort_link(@q, :storage) %></th>
      <th><%= sort_link(@q, :subnet) %></th>
      <th><%= sort_link(@q, :ip, "IP") %></th>
      <th><%= sort_link(@q, :nsg, "NSG") %></th>
      <th><%= sort_link(@q, :nsg_resource_group, "NSG Resource Group") %></th>
      <th><%= sort_link(@q, :created_at, "Added") %></th>
      <th><%= sort_link(@q, :updated_at) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @systems.each do |system| %>
      <tr>
        <td><%= system.name %></td>
        <td><%= system.resource_group %></td>
        <td><%= system.location %></td>
        <td><%= system.availability_set %></td>
        <td><%= system.operating_system %></td>
        <td><%= system.vm_size %></td>
        <td><%= system.operating_system_version %></td>
        <td><%= system.storage %></td>
        <td><%= system.subnet %></td>
        <td><%= system.ip %></td>
        <td><%= system.nsg %></td>
        <td><%= system.nsg_resource_group %></td>
        <td><%= system.created_at.strftime('%m/%d/%Y') %></td>
        <td><%= system.updated_at.strftime('%m/%d/%Y') %></td>
        <td><%= link_to 'Show', system %></td>
        <td><%= link_to 'Edit', edit_system_path(system) %></td>
        <td><%= link_to 'Destroy', system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New System', new_system_path %>